name: Continous integration
on: [push]
jobs:
  Run-tests:
    #runs-on: ubuntu-latest
    runs-on: windows-latest # Changed from ubuntu-latest to windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'
      env:
          #AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
          AGENT_TOOLSDIRECTORY: C:\hostedtoolcache\ # Updated path for Windows
    - name: Install
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        cd src; nose2 --with-coverage pySubnetSB_tests
        coverage-badge -o coverage.svg
        cd ..
    - name: Install package
      run: |
        pip install pySubnetSB
    - name: Run notebook
      run: |
        python scripts/make_example_script.py
        ipython examples/api_basics.py
