name: Continous integration
on: [push]
jobs:
  Run-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        cd src; nose2 --with-coverage --reporter=json-summary pySubnetSB_tests
        coverage-badge -o coverage.svg
        cd ..
    - name: Install package
      run: |
        pip install pySubnetSB
    - name: Run notebook
      run: |
        python scripts/make_example_script.py
        ipython examples/api_basics.py
    - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
       if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
       uses: we-cli/coverage-badge-action@main
