name: Continous integration
on: [push]
jobs:
  Run-308:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.8'
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install
      run: |
        pip install --upgrade pip
        pip install jupyterlab
        pip install pySubnetSB
    - name: Run script
      run: |
        ipython examples/api_basics.py
  Run-310:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install
      run: |
        pip install --upgrade pip
        pip install jupyterlab
        pip install pySubnetSB
    - name: Run script
      run: |
        ipython examples/api_basics.py
  Run-312:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.12'
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install
      run: |
        pip install --upgrade pip
        pip install jupyterlab
        pip install pySubnetSB
    - name: Run script
      run: |
        ipython examples/api_basics.py
