name: Continous integration
on: [push]
jobs:
  #
  Run-309:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install
      run: |
        pip install --upgrade pip
        pip install jupyterlab
        pip install pySubnetSB
    - name: Run script
      run: |
        ipython examples/api_basics_noplot.py
  #
  Run-310:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install
      run: |
        pip install --upgrade pip
        pip install jupyterlab
        pip install pySubnetSB
    - name: Run script
      run: |
        ipython examples/api_basics_noplot.py
  #
  Run-311:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.11'
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install
      run: |
        pip install --upgrade pip
        pip install jupyterlab
        pip install pySubnetSB
    - name: Run script
      run: |
        ipython examples/api_basics_noplot.py
  #
  Run-312:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.12'
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install
      run: |
        pip install --upgrade pip
        pip install jupyterlab
        pip install pySubnetSB
    - name: Run script
      run: |
        ipython examples/api_basics_noplot.py
