name: Continous integration
on: [push]
jobs:
  #
  Run-309:
    runs-on: windows-latest # Changed from ubuntu-latest to windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'
      env:
          AGENT_TOOLSDIRECTORY: C:\hostedtoolcache\ # Updated path for Windows
    - name: Install package
      run: |
        pip install jupyterlab
        pip install pySubnetSB
    - name: Run notebook
      run: |
        ipython examples/api_basics_noplot.py
  #
  Run-310:
    runs-on: windows-latest # Changed from ubuntu-latest to windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'
      env:
          AGENT_TOOLSDIRECTORY: C:\hostedtoolcache\ # Updated path for Windows
    - name: Install package
      run: |
        pip install jupyterlab
        pip install pySubnetSB
    - name: Run notebook
      run: |
        ipython examples/api_basics_noplot.py
  #
  Run-311:
    runs-on: windows-latest # Changed from ubuntu-latest to windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
          python-version: '3.11'
      env:
          AGENT_TOOLSDIRECTORY: C:\hostedtoolcache\ # Updated path for Windows
    - name: Install package
      run: |
        pip install jupyterlab
        pip install pySubnetSB
    - name: Run notebook
      run: |
        ipython examples/api_basics_noplot.py
  #
  Run-312:
    runs-on: windows-latest # Changed from ubuntu-latest to windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
          python-version: '3.12'
      env:
          AGENT_TOOLSDIRECTORY: C:\hostedtoolcache\ # Updated path for Windows
    - name: Install package
      run: |
        pip install jupyterlab
        pip install pySubnetSB
    - name: Run notebook
      run: |
        ipython examples/api_basics_noplot.py
